+incdir+../rtl/regfile/
+incdir+../rtl/uart/

../rtl/regfile/regs.v
../rtl/uart/rtl/baudrate.v
../rtl/uart/rtl/transmitter.v
../rtl/uart/rtl/receiver.v
../rtl/uart/rtl/uart.v
../rtl/i_mux.sv
../rtl/ram.sv
../rtl/rom.sv
../rtl/fd.sv
../rtl/ex.sv
../rtl/core.sv
../rtl/d_mux.sv
../rtl/misc/fifo.sv
../rtl/uart_sw_upgrader.sv
../rtl/uart_mgr.sv
../rtl/soc.sv
../tb/tb_soc.sv
