+incdir+../rtl/regfile/
+incdir+../rtl/uart/

../rtl/regfile/regs.v
../rtl/uart/rtl/baudrate.v
../rtl/uart/rtl/transmitter.v
../rtl/uart/rtl/receiver.v
../rtl/uart/rtl/uart.v
../rtl/i_mux.sv
../rtl/if_fifo.sv
../rtl/ram.sv
../rtl/rom.sv
../rtl/xrv_i_decompress.sv
../rtl/xrv_ctrl.sv
../rtl/xrv_mult.sv
../rtl/xrv_div.sv
../rtl/xrv_id.sv
../rtl/xrv_if.sv
../rtl/xrv_ex.sv
../rtl/xrv_core.sv
../rtl/d_mux.sv
../rtl/misc/fifo.sv
../rtl/misc/pll.sv
../rtl/uart_sw_upgrader.sv
../rtl/uart_mgr.sv
../rtl/soc.sv
../tb/tb_soc.sv
../tb/tb_mul_div.sv
